### PR TITLE
Add cases by city graph

### PR DESCRIPTION
**Pull request by n1r1**
I think it's valuable for people to see the infections trend in their city.
Current graphs mainly represents total status.

So this new addition mainly added to answer questions like: is there currently massive outbreak in my city or maybe there are no new infections lately.

### CODE REVIEW

**Comment by n1r1** [comment]
@idandrd can you please review?

**Review by idandrd — APPROVED** [review]
Very nice, thank you!

**Comment by idandrd** [comment]
@n1r1 Thanks for your help!
Would it be ok by you if I copied your chart to our own Datawrapper account, so we can maintain it further? we will keep the original credit of course.

**Comment by n1r1** [comment]
Sure. No problem.

**Pull request merged**
